CREATE TABLE departments
(
  department_id INTEGER PRIMARY KEY generated by default AS identity,
  department_name VARCHAR(100) NOT NULL,
  manager INTEGER REFERENCES employees(employee_id) unique -- Foreign key
);

INSERT INTO departments
  (department_name, manager)
  VALUES
    ('Administration', 2),
    ('Merchandising', 7),
    ('Customer Service', 8),
    ('Marketing', 9);